# .github/workflows/norm-v2.yml
name: norm-v2
on: [push, pull_request]

jobs:

  norminette_v2_job:
    runs-on: ubuntu-latest
    name: norminette v2
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v2